name: Build and Manual Release

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        default: '1.0.0'
        type: string

# Add explicit permissions for creating releases
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: OllamaCraft
        path: target/ollamacraft-*.jar

  release:
    needs: build
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Find JAR file
      id: find_jar
      run: |
        jar_path=$(find target -name "ollamacraft-*.jar" | head -n 1)
        if [ -z "$jar_path" ]; then
          echo "No JAR file found!"
          exit 1
        fi
        echo "Found JAR: $jar_path"
        echo "jar_path=$jar_path" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.event.inputs.version }}
        name: OllamaCraft v${{ github.event.inputs.version }}
        draft: false
        prerelease: false
        files: ${{ steps.find_jar.outputs.jar_path }}
        body: |
          # OllamaCraft v${{ github.event.inputs.version }}
          
          ## Installation
          
          1. Download the JAR file
          2. Place it in your server's `plugins` directory
          3. Start or restart your server
          
          See the [README](https://github.com/aguara-guazu/OllamaCraft/blob/main/README.md) for more details.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}